[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist/web-analytics/browser"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

 
 
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200